name: Common-UI-Trigger Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Latest Commit Message Environment Variable
        id: commit-info
        run: echo "LATEST_COMMIT_EN=$(git log -1 --format=%s)" >> $GITHUB_ENV

      - name: Fetch latest commits from sc-ui-common
        run: |
          # Define variables for the repo and branches
          REPO="abhijeetpoonia/my-ui-repo"
          BRANCH_EN="Prod-EN"
          BRANCH_FR="Prod-FR"
          API_URL="https://api.github.com/repos/$REPO/commits?sha="
          # Fetch latest commits from Prod-EN and Prod-FR branches
          curl -X GET "${API_URL}${BRANCH_EN}" -H "Authorization: Bearer ${{ secrets.TOKEN }}" -o latest-commit-prod-en.json
          curl -X GET "${API_URL}${BRANCH_FR}" -H "Authorization: Bearer ${{ secrets.TOKEN }}" -o latest-commit-prod-fr.json

      - name: Print JSON Outputs
        run: |
          echo "Prod-EN JSON Output:"
          cat latest-commit-prod-en.json
          echo "Prod-FR JSON Output:"
          cat latest-commit-prod-fr.json

      - name: Extract Commit Messages
        run: |
          # Extract commit messages from the JSON files based on actual structure
          LATEST_COMMIT_PROD_EN=$(jq -r '.[0].commit.message' < latest-commit-prod-en.json || jq -r '.commit.message' < latest-commit-prod-en.json)
          LATEST_COMMIT_PROD_FR=$(jq -r '.[0].commit.message' < latest-commit-prod-fr.json || jq -r '.commit.message' < latest-commit-prod-fr.json)
          # Set extracted values as environment variables
          echo "LATEST_COMMIT_PROD_EN=${LATEST_COMMIT_PROD_EN}" >> $GITHUB_ENV
          echo "LATEST_COMMIT_PROD_FR=${LATEST_COMMIT_PROD_FR}" >> $GITHUB_ENV

      - name: Trigger UI-Test workflow in sc-ui-common for Prod-EN
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOKEN }}
          repository: abhijeetpoonia/my-ui-repo
          event-type: trigger-prod-EN
          client-payload: |
            {
              "data": [
                {
                  "ref": "main",
                  "commit_message": "${{ env.LATEST_COMMIT_EN }}",
                  "sc_ui_dispatch_commits": {
                    "Prod-EN": "${{ env.LATEST_COMMIT_PROD_EN }}"
                  },
                  "trigger-branch": "Prod-EN"
                }
              ]
            }

      - name: Trigger UI-Test workflow in sc-ui-common for Prod-FR
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOKEN }}
          repository: abhijeetpoonia/my-ui-repo
          event-type: trigger-prod-FR
          client-payload: |
            {
              "data": [
                {
                  "ref": "main",
                  "commit_message": "${{ env.LATEST_COMMIT_EN }}",
                  "sc_ui_dispatch_commits": {
                    "Prod-FR": "${{ env.LATEST_COMMIT_PROD_FR }}"
                  },
                  "trigger-branch": "Prod-FR"
                }
              ]
            }
